CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730144034_InitialCreate') THEN
    CREATE TABLE car_brands (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(80) NOT NULL,
        sort_order integer NOT NULL,
        CONSTRAINT pk_car_brands PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730144034_InitialCreate') THEN
    CREATE TABLE faqs (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        question character varying(200) NOT NULL,
        answer character varying(1200) NOT NULL,
        sort_order integer NOT NULL,
        CONSTRAINT pk_faqs PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730144034_InitialCreate') THEN
    CREATE TABLE localities (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(80) NOT NULL,
        city character varying(80) NOT NULL,
        is_active boolean NOT NULL,
        sort_order integer NOT NULL,
        CONSTRAINT pk_localities PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730144034_InitialCreate') THEN
    CREATE TABLE services (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        slug character varying(60) NOT NULL,
        name character varying(120) NOT NULL,
        tagline character varying(200) NOT NULL,
        icon character varying(40) NOT NULL,
        starting_price integer NOT NULL,
        list_price integer NOT NULL,
        duration character varying(60) NOT NULL,
        warranty character varying(120) NOT NULL,
        is_new boolean NOT NULL,
        is_bestseller boolean NOT NULL,
        sort_order integer NOT NULL,
        CONSTRAINT pk_services PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730144034_InitialCreate') THEN
    CREATE TABLE testimonials (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        quote character varying(400) NOT NULL,
        author character varying(80) NOT NULL,
        car character varying(80) NOT NULL,
        locality character varying(80) NOT NULL,
        rating integer NOT NULL,
        sort_order integer NOT NULL,
        CONSTRAINT pk_testimonials PRIMARY KEY (id),
        CONSTRAINT ck_testimonials_rating CHECK (rating BETWEEN 1 AND 5)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730144034_InitialCreate') THEN
    CREATE TABLE wash_plans (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(80) NOT NULL,
        blurb character varying(200) NOT NULL,
        price_per_month integer NOT NULL,
        list_price_per_month integer NOT NULL,
        wash_count character varying(120) NOT NULL,
        is_popular boolean NOT NULL,
        sort_order integer NOT NULL,
        CONSTRAINT pk_wash_plans PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730144034_InitialCreate') THEN
    CREATE TABLE car_models (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        car_brand_id integer NOT NULL,
        name character varying(80) NOT NULL,
        body_type character varying(20) NOT NULL,
        sort_order integer NOT NULL,
        CONSTRAINT pk_car_models PRIMARY KEY (id),
        CONSTRAINT fk_car_models_car_brands_car_brand_id FOREIGN KEY (car_brand_id) REFERENCES car_brands (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730144034_InitialCreate') THEN
    CREATE TABLE bookings (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        reference character varying(24) NOT NULL,
        customer_name character varying(80) NOT NULL,
        phone character varying(15) NOT NULL,
        email character varying(160),
        car_brand character varying(80) NOT NULL,
        car_model character varying(80) NOT NULL,
        body_type character varying(20) NOT NULL,
        service_id integer NOT NULL,
        locality character varying(80) NOT NULL,
        preferred_date date NOT NULL,
        preferred_slot character varying(40) NOT NULL,
        notes character varying(400),
        quoted_price integer NOT NULL,
        status character varying(20) NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (now()),
        CONSTRAINT pk_bookings PRIMARY KEY (id),
        CONSTRAINT fk_bookings_services_service_id FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730144034_InitialCreate') THEN
    CREATE TABLE service_includes (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        service_id integer NOT NULL,
        text character varying(200) NOT NULL,
        sort_order integer NOT NULL,
        CONSTRAINT pk_service_includes PRIMARY KEY (id),
        CONSTRAINT fk_service_includes_services_service_id FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730144034_InitialCreate') THEN
    CREATE TABLE plan_features (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        wash_plan_id integer NOT NULL,
        text character varying(200) NOT NULL,
        sort_order integer NOT NULL,
        CONSTRAINT pk_plan_features PRIMARY KEY (id),
        CONSTRAINT fk_plan_features_wash_plans_wash_plan_id FOREIGN KEY (wash_plan_id) REFERENCES wash_plans (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730144034_InitialCreate') THEN
    CREATE INDEX ix_bookings_phone ON bookings (phone);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730144034_InitialCreate') THEN
    CREATE INDEX ix_bookings_preferred_date_status ON bookings (preferred_date, status);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730144034_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_bookings_reference ON bookings (reference);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730144034_InitialCreate') THEN
    CREATE INDEX ix_bookings_service_id ON bookings (service_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730144034_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_car_brands_name ON car_brands (name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730144034_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_car_models_car_brand_id_name ON car_models (car_brand_id, name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730144034_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_localities_city_name ON localities (city, name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730144034_InitialCreate') THEN
    CREATE INDEX ix_plan_features_wash_plan_id ON plan_features (wash_plan_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730144034_InitialCreate') THEN
    CREATE INDEX ix_service_includes_service_id ON service_includes (service_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730144034_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_services_slug ON services (slug);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730144034_InitialCreate') THEN
    CREATE UNIQUE INDEX ix_wash_plans_name ON wash_plans (name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260730144034_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260730144034_InitialCreate', '10.0.10');
    END IF;
END $EF$;
COMMIT;

